version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:${NODE_ENV} api
    env_file:
      - ./apps/api/.env
    ports:
      - 4000:4000
    volumes:
      - ./apps/api:/usr/src/app/apps/api:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats
      - user

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:${NODE_ENV} user
    env_file:
      - ./.env
      - ./apps/user/.env
    ports:
      - 4001:4001
    volumes:
      - ./apps/user:/usr/src/app/apps/user:z
      - ./libs/common:/usr/src/app/libs/common:z
      - ./databases/sqlite:/usr/src/app/databases/sqlite:z
    depends_on:
      - nats

  transfer:
    build:
      context: .
      dockerfile: ./apps/transfer/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:${NODE_ENV} transfer
    env_file:
      - ./.env
      - ./apps/transfer/.env
    ports:
      - 4002:4002
    volumes:
      - ./apps/transfer:/usr/src/app/apps/transfer:z
      - ./libs/common:/usr/src/app/libs/common:z
      - ./databases/sqlite:/usr/src/app/databases/sqlite:z
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
